### ISSUE TITLE
Best Practices - SCSS Styleguide

### ISSUE THREAD

**Issue by Nerdy-Girl** [7ninjas/scss-mixins#27]
Please add best practices document for project
- [x] reboot.css or normalize.css
- [x] help yourself with <b>stylelint</b>
- [x] naming conventions
  - [x] don't reuse parent's class name in child's classes
  - [x] keep order of declaring classes and it states (firstly declare state of current class then declare nested children ie. .active is higher than nested child class)
  - [x] class should be described by entity, behaviour, state or look
  - [x] camelCase in react, rest in hypen-case
  - [x] color naming
- [x] spaces and indentations (2) (no tabs)
- [x] use mixins for margins and paddings
- [x] assign value to variable in variables.scss
- [x] first use mixins, then override styles (if needed)
- [x] never wander too deep -> don't go more than 3 levels deep (add stylelint rule)
- [x] don't style elements, style classes
- [x] don't use id if not needed
- [x] global styles
- [x] styles from another packages
- [x] creating JavaScript-specific classes to bind to, prefixed with .js-
- [x] overusing unclassed divs

**Comment by Nerdy-Girl** [comment]
- use stylelint
- Naming Conventions
  - don't reuse parent's class name in child's classes
  - keep order of declaring classes and it states (firstly declare state of current class then declare nested children ie. `.active` is higher than nested child class)
  - class should be described by entity, behaviour, state or look
- two (2) spaces indents, no tabs
- camelCase in react, rest in hypen-case
- use mixins for margins and paddings
- don't use hardcoded values in scss
- assign value to variable in variables.scss
- first use mixins, then override styles (if needed)
- never go more than 3 levels deep (add stylelint rule)

**Comment by ArekRado** [comment]
- https://github.com/airbnb/javascript
- don't style elements, style classes
- don't use id if not needed
- how to use with react
- global styles
- styles from another packages

**Comment by JSerhii** [comment]
- color naming
- creating JavaScript-specific classes to bind to, prefixed with `.js-`

**Comment by CodeMeNatalie** [comment]
- [ ] help youself with <b>stylelint</b>
- [ ] naming conventions
  - [ ] don't reuse parent's class name in child's classes
  - [ ] keep order of declaring classes and it states (firstly declare state of current class then declare nested children ie. .active is higher than nested child class)
  - [ ] class should be described by entity, behaviour, state or look
  - [ ] camelCase in react, rest in hypen-case
  - [ ] color naming
- [ ] spaces and indentations (2) (no tabs)
- [ ] use mixins for margins and paddings
- [ ] don't use hardcoded values in scss
- [ ] assign value to variable in variables.scss
- [ ] first use mixins, then override styles (if needed)
- [ ] never wander too deep -> don't go more than 3 levels deep (add stylelint rule) (red hood example in being lost in code)
- [ ] don't style elements, style classes
- [ ] don't use id if not needed
- [ ] global styles
- [ ] styles from another packages
- [ ] creating JavaScript-specific classes to bind to, prefixed with .js-

**Comment by ArekRado** [comment]
- [ ] - reboot.css or normalize.css 
- [ ] - getting started - how to create first project and, how to configure it, how to style my first component
- [ ] - how to use typography

**Comment by Nerdy-Girl** [comment]
@ArekRado 
> - [ ] - how to use typography

shouldn't this be in typography documents? or you have special purpose and want it to be described? (example pls)

also this 

> - [ ] - getting started - how to create first project and, how to configure it, how to style my first component

shouldn't be in Best Practices - SCSS Styleguide in my opinion

I think we should rename this issue for 'Best Practices - SCSS Styleguide' so it won't be so generic
