### ISSUE TITLE
Wrong arguments in triangle mixin for pseudo mixin

### ISSUE THREAD

**Issue by Philips7** [7ninjas/scss-mixins#92]
![image](https://user-images.githubusercontent.com/19551727/37396334-e434f8e6-2778-11e8-9e6f-4c2c50b1e9a9.png)
![image](https://user-images.githubusercontent.com/19551727/37396378-013b1fe2-2779-11e8-9908-a8d722d10007.png)
Nothing to add... :)

**Comment by ArekRado** [comment]
next time please write more information to not waste our time
