### ISSUE TITLE
Proposal - cover background image

### ISSUE THREAD

**Issue by Nerdy-Girl** [7ninjas/scss-mixins#97]
How about adding mixin which can indicate how background image will work?
Many times we write
```
.example-class {
  background-image: url('...');
  background-size: cover;
  background-position: center;
}
```

Example: 
```
.example-class {
  @include background-image($source: '...', $size: cover, $position: center);
}
```

* as a source we would just past path to file, and inside mixin it would put variable into `url` tag?

It would faster our work. What do you think about it?

**Comment by JSerhii** [comment]
You can use shorthand background property instead 
Example:
```css
background: #ffffff url("img_tree.png") no-repeat right top;
```
